### ISSUE TITLE
Tracking issue: Add non-incremental MCMPC benchmarks

### ISSUE THREAD

**Issue by hansjoergschurr** [SMT-LIB/benchmark-submission-2023#3]
_This is an issue to track the progress of integrating the benchmarks submitted to the 2022 repository [here](https://github.com/SMT-LIB/benchmark-submission-2022/pull/15).  Due to the size of the contribution it is handled by us out-of-band._

In the original submission [maxzinkus](https://github.com/maxzinkus) wrote:

I'm submitting this PR with a number of `smt2` files generated as part of my research in quantifying the privacy/entropy loss of secret data in [MPC](https://en.wikipedia.org/wiki/Secure_multi-party_computation) protocols.

These non-incremental files are the result of optimizing `Max#SAT`-style queries to the solver which constrain the secret information space given information on the outputs of arbitrary functions. In my evaluation, I enumerate a set of exemplar functionalities and run the iterative attack generation procedure over them. These files are the steps of each iteration of optimizing `#SAT` (model counting) queries using universal hash functions following [Fremont et al](https://ojs.aaai.org/index.php/AAAI/article/view/11138). Each subdirectory of `20221012-MCMPC` is a different functionality I tested on. They vary widely in complexity, and indeed a number of them are trivial and a number of them are unsolved in the running time I allotted (days of CPU time, in some cases).

A small number of files (8 of them) over 50MB are gzip compressed for convenience. While these files were generated over the course of months, I set the date to they day I collated and prepared them for submission. I'm now getting around to pushing them to GitHub -- a little late, but hopefully not an issue if anyone was awaiting them for any reason.

`quick-check.sh` succeeds on all of them, and `dolmen -i smt2 --check-headers=true --header-lang-version=2.6` either succeeds or times out, but encounters no errors in my test.

I hope that these can be useful within the highly valuable `QF_BV` domain, where immediate transformations from compiled binaries and other programs are readily available for research and industrial use.

**Comment by hansjoergschurr** [comment]
Here is a tarball with the submitted files: https://homepage.cs.uiowa.edu/~hschrr/SMT-LIB/2023/20221012-MCMPC.tar.bz2

**Comment by hansjoergschurr** [comment]
I checked them locally with the `quick-check.sh` script and and dolmen.  They pass.

**Comment by hansjoergschurr** [comment]
Now it's also in the SMT-LIB pending repository. https://clc-gitlab.cs.uiowa.edu:2443/SMT-LIB-benchmarks-tmp/pending-2023

**Comment by xzinkus** [comment]
Hey- my apologies and thank you for pushing this through. I was unable to get cycles on the compute instance to run dolmen, then when I finally had them I got lost in an opam dependency rabbit hole. A clean install and eventually follow-up running dolemn confirmed your findings. Close as resolved if the benchmarks are now included?

**Comment by hansjoergschurr** [comment]
I checked the benchmarks in the `pending-2023` repository in the same way as the benchmarks here and moved them from the `TODO` sub folder into the main folder.

**Comment by mpreiner** [comment]
Benchmarks are now merged into the develop-2023 branch.
